[package]
name = "rinf-router"
version = "1.1.0"
description = "Router and handler framework for RINF-based Flutter <> Rust apps"
authors = ["Frederik Haaning <fh@frederikhaaning.dk>"]
edition = "2024"
repository = "https://github.com/asaphaaning/rinf-router"
readme = "README.md"
keywords = [
    "rinf",
    "flutter",
    "router"
]

categories = [
    "asynchronous",
    "rust-patterns",
]

license = "Apache-2.0"
rust-version = "1.85.0"

[features]
default = []
logging = ["dep:tracing", "tracing/log"]
tracing = ["logging", "tracing/tracing-attributes", "tracing/attributes"]

[dependencies]
async-trait = "0.1"
futures = "0.3"
rinf = "8.6.0"
serde = { version = "1.0", features = ["derive"] }
tracing = { version = "0.1", default-features = false, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.41", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time"
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.41", features = [
    "macros",
    "rt",
    "sync",
    "time"
] }


[dev-dependencies]
serial_test = "3.2"