[package]
name = "rinf-router"
version = "1.0.0"
description = "Router and handler framework for RINF-based Flutter <> Rust apps"
authors = ["Frederik Haaning <fh@frederikhaaning.dk>"]
edition = "2024"
repository = "https://github.com/asaphaaning/rinf-router"
readme = "README.md"
keywords = [
    "rinf",
    "flutter",
    "router"
]
categories = [
    "asynchronous",
    "rust-patterns",
]
license = "Apache-2.0"
rust-version = "1.85.0"

[dependencies]
async-trait = "0.1"
rinf = "8.3.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.41", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time"
] }

[dev-dependencies]
serial_test = "3.2"
futures = "0.3"