unstable_features = true
imports_granularity = "One"
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
# Use braces for import groups
use_field_init_shorthand = true

# Comment formatting
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Additional settings
format_strings = true
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
reorder_impl_items = true